# Catch all requests with an invalid HOST header
server {
    server_name "";
    listen      80 default_server;
    return      400;
}

server {
    listen 80;
    server_name localhost 127.0.0.1 staging.talentcloud.asia;

    keepalive_timeout 5;
    client_max_body_size 1G;

    location / {
        root /usr/share/nginx/html;
        # For React Router
        try_files $uri $uri/ /index.html;
    }
}
