# Dockerfile.backend
FROM python:3.12-alpine

WORKDIR /app

RUN apt-get update && apt-get install -y netcat gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements/development.txt .
RUN pip install --no-cache-dir -r development.txt

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["sh", "-c", "python manage.py migrate && gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"]
