# Generated by Django 5.1.1 on 2025-05-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The official name of the company.', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the company name.', max_length=255, unique=True)),
                ('address', models.CharField(blank=True, help_text='The address of the company.', max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, help_text="URL to the company's logo.", max_length=1024, null=True)),
                ('website', models.URLField(blank=True, help_text='The official website URL of the company.', max_length=1024, null=True)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the company, its mission, and culture.', null=True)),
                ('industry', models.CharField(blank=True, help_text='The industry the company operates in (e.g., Technology, Healthcare).', max_length=100, null=True)),
                ('size', models.CharField(blank=True, help_text="The size of the company (e.g., '1-10 employees', '51-200 employees').", max_length=50, null=True)),
                ('tagline', models.CharField(blank=True, help_text='A short, catchy tagline for the company.', max_length=150, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='A general contact email for the company.', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='A general contact phone number for the company.', max_length=20, null=True)),
                ('founded_date', models.DateField(blank=True, help_text='The date the company was founded.', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the company profile has been verified by the platform.')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
