import {
  BehenceIcon,
  FaceBookIcon,
  GitHubIcon,
  LinkedInIcon,
  PortfolioIcon,
} from "@/constants/socialSvgs";
import { MONTHDATA } from "./CommonData";

export const fields: any[] = [
  {
    fieldName: "name",
    placeholder: "Choose your own nickname",
    isError: (form: any) => !!form.formState.errors.displayName,
    required: true,
    requiredLabel: true,
    languageName: "userProfile",
    type: "text",
    showPasswordIcon: null,
    hidePasswordIcon: null,
    showLetterCount: true, // New prop to show/hide letter count
    maxLength: 20,
  },
  {
    fieldName: "name",
    placeholder: "Choose your own nickname",
    isError: (form: any) => !!form.formState.errors.displayName,
    required: true,
    requiredLabel: true,
    languageName: "userProfile",
    type: "text",
    showPasswordIcon: null,
    hidePasswordIcon: null,
    showLetterCount: true, // New prop to show/hide letter count
    maxLength: 20,
  },
  {
    fieldName: "username",
    placeholder: "Set your ID so that users can search for you",
    isError: (form: any) => !!form.formState.errors.userName,
    required: true,
    requiredLabel: true,
    languageName: "userProfile",
    type: "text",
    showPasswordIcon: null,
    hidePasswordIcon: null,
    showLetterCount: true, // New prop to show/hide letter count
    maxLength: 20,
    description: true,
    descriptionText: "* Username can only be changed once per 7 days",
  },
  {
    fieldName: "tagline",
    placeholder: "eg. Frontend Developer Lead at Google",
    isError: (form: any) => !!form.formState.errors.userName,
    required: true,
    requiredLabel: true,
    languageName: "userProfile",
    type: "text",
    showPasswordIcon: null,
    hidePasswordIcon: null,
    showLetterCount: true, // New prop to show/hide letter count
    maxLength: 60,
    description: true,
    descriptionText: "The community will see job title after your name",
  },
  {
    type: "select",
    fieldName: "specialization_id",
    placeholder: "eg. Development & IT/ Frontend Developer",
    required: true,
    labelName: "Specialization Role",
    requiredLabel: true,
    isError: (form: any) => !!form.formState.errors?.specialization,
    data: MONTHDATA,
    descriptionText:'System use only for job filtering and will not be visible to users.'
  },
  {
    type: "select",
    fieldName: "experience_level_id",
    placeholder: "eg. Junior Level",
    labelName: "Level",
    requiredLabel: true,
    required: true,
    isError: (form: any) => !!form.formState.errors?.experience_level,
    data: MONTHDATA,
  },
  {
    type: "select",
    fieldName: "experience_level_id",
    placeholder: "eg. Less than 1 year",
    labelName: "Years of Experience",
    requiredLabel: true,
    required: true,
    isError: (form: any) => !!form.formState.errors?.experience_level,
    data: MONTHDATA,
  },
  {
    fieldName: "country_code",
    placeholder: "phoneNumber",
    isError: (form: any) => !!form.formState.error.country_code,
    required: true,
    requiredLabel: true,
    languageName: "userProfile",
    type: "phoneNumber",
    showPasswordIcon: null,
    hidePasswordIcon: null,
    chilField: [
      {
        fieldName: "phone_number",
        placeholder: "123456789",
        isError: (form: any) => !!form.formState.errors.phone_number,
        required: false,
        requiredLabel: false,
        languageName: "stepTwo",
        type: "text",
        showPasswordIcon: null,
        hidePasswordIcon: null,
      },
    ],
  },
  {
    fieldName: "date_of_birth",
    placeholder: "Birthday",
    isError: (form: any) => !!form.formState.errors.date_of_birth,
    required: false,
    type: "date",
    fieldWidth: "",
    fieldHeight: "",
    languageName: "userProfile",
  },
  {
    fieldName: "address",
    placeholder: "Location",
    isError: (form: any) => !!form.formState.errors.location,
    required: false,
    requiredLabel: true,
    languageName: "userProfile",
    type: "text",
    showPasswordIcon: null,
    hidePasswordIcon: null,
    showLetterCount: true, // New prop to show/hide letter count
    maxLength: 30,
  },
  {
    fieldName: "bio",
    placeholder: "A brief introduction about yourself",
    isError: (form: any) => !!form.formState.errors.bio,
    required: false,
    requiredLabel: true,
    languageName: "userProfile",
    type: "textArea",
    showPasswordIcon: null,
    hidePasswordIcon: null,
    showLetterCount: true, // New prop to show/hide letter count
    maxLength: 250,
    height: "h-[128px]",
  },
];

export const socialLinkFields: SocialLinkFieldType[] = [
  {
    fieldName: "facebook_url",
    isError: (form: any) => !!form.formState.errors.displayName,
    startIcon: <FaceBookIcon />,
    languageName: "userProfile",
  },
  {
    fieldName: "linkedin_url",
    isError: (form: any) => !!form.formState.errors.displayName,
    startIcon: <LinkedInIcon />,
    languageName: "userProfile",
  },
  {
    fieldName: "github_url",
    isError: (form: any) => !!form.formState.errors.displayName,
    startIcon: <GitHubIcon />,
    languageName: "userProfile",
  },
  {
    fieldName: "behance_url",
    isError: (form: any) => !!form.formState.errors.displayName,
    startIcon: <BehenceIcon />,
    languageName: "userProfile",
  },
  {
    fieldName: "portfolio_url",
    isError: (form: any) => !!form.formState.errors.displayName,
    startIcon: <PortfolioIcon />,
    languageName: "userProfile",
  },
];
