# Generated by Django 5.1.1 on 2025-09-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_company_image_urls'),
        ('job_posting', '0008_rename_cover_letter_jobapplication_cover_letter_url_and_more'),
        ('job_seekers', '0035_alter_university_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this applicant was favorited', null=True)),
                ('company', models.ForeignKey(help_text='The company this favorite belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_applicants', to='companies.company')),
                ('job_application', models.ForeignKey(help_text='The job application that was favorited', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='job_posting.jobapplication')),
                ('user', models.ForeignKey(help_text='The user who marked this applicant as favorite', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_applicants', to='job_seekers.jobseeker')),
            ],
            options={
                'verbose_name': 'Favorite Applicant',
                'verbose_name_plural': 'Favorite Applicants',
                'db_table': 'ni_dashboard_favorite_applicants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'company'], name='idx_user_company_fav'), models.Index(fields=['company', 'created_at'], name='idx_company_created_fav'), models.Index(fields=['job_application'], name='idx_job_application_fav')],
                'unique_together': {('user', 'company', 'job_application')},
            },
        ),
    ]
