# Generated by Django 5.1.1 on 2025-09-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_company_image_urls'),
        ('job_seekers', '0035_alter_university_name'),
        ('ni_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteJobSeeker',
            new_name='FavouriteJobSeeker',
        ),
    ]
