# Generated by Django 5.2.6 on 2025-09-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ni_dashboard', '0002_rename_favoritejobseeker_favouritejobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritejobseeker',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
