# Generated by Django 5.1.1 on 2025-08-14 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_channel', '0005_alter_message_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('generic', 'GENERIC'), ('account_created', 'ACCOUNT_CREATED'), ('job_posted', 'JOB_POSTED'), ('job_applied', 'JOB_APPLIED'), ('application_status_update', 'APPLICATION_STATUS_UPDATE'), ('company_approved', 'COMPANY_APPROVED'), ('company_rejected', 'COMPANY_REJECTED'), ('admin_company_registration', 'ADMIN_COMPANY_REGISTRATION'), ('admin_user_registration', 'ADMIN_USER_REGISTRATION'), ('admin_job_posting', 'ADMIN_JOB_POSTING'), ('admin_system_alert', 'ADMIN_SYSTEM_ALERT'), ('admin_platform_activity', 'ADMIN_PLATFORM_ACTIVITY'), ('admin_report_generated', 'ADMIN_REPORT_GENERATED'), ('admin_company_verification', 'ADMIN_COMPANY_VERIFICATION'), ('admin_content_moderation', 'ADMIN_CONTENT_MODERATION'), ('admin_violation_report', 'ADMIN_VIOLATION_REPORT'), ('admin_maintenance', 'ADMIN_MAINTENANCE'), ('application_status_changed', 'APPLICATION_STATUS_CHANGED'), ('new_job_matches', 'NEW_JOB_MATCHES'), ('profile_completion_reminder', 'PROFILE_COMPLETION_REMINDER'), ('profile_viewed', 'PROFILE_VIEWED'), ('interview_scheduled', 'INTERVIEW_SCHEDULED'), ('interview_reminder', 'INTERVIEW_REMINDER'), ('job_expiring_soon', 'JOB_EXPIRING_SOON'), ('weekly_job_digest', 'WEEKLY_JOB_DIGEST'), ('saved_job_update', 'SAVED_JOB_UPDATE'), ('application_deadline_reminder', 'APPLICATION_DEADLINE_REMINDER'), ('application_submitted', 'APPLICATION_SUBMITTED'), ('application_pending', 'APPLICATION_PENDING'), ('application_under_review', 'APPLICATION_UNDER_REVIEW'), ('application_shortlisted', 'APPLICATION_SHORTLISTED'), ('application_interview_scheduled', 'APPLICATION_INTERVIEW_SCHEDULED'), ('application_accepted', 'APPLICATION_ACCEPTED'), ('application_offer_extended', 'APPLICATION_OFFER_EXTENDED'), ('application_rejected', 'APPLICATION_REJECTED'), ('application_withdrawn', 'APPLICATION_WITHDRAWN')], help_text='Type of notification this template is for', max_length=50)),
                ('channel', models.CharField(choices=[('email', 'EMAIL'), ('websocket', 'WEBSOCKET'), ('both', 'BOTH'), ('push', 'PUSH')], help_text='Channel this template applies to', max_length=20)),
                ('subject_template', models.CharField(blank=True, help_text='Email subject template with placeholders like {user_name}, {company_name}', max_length=255)),
                ('email_template_name', models.CharField(blank=True, help_text="Path to the HTML email template file (e.g., 'emails/job_posted.html')", max_length=255)),
                ('title_template', models.CharField(blank=True, help_text='Title template for in-app notifications with placeholders', max_length=255)),
                ('message_template', models.TextField(blank=True, help_text='Message template for in-app notifications with placeholders')),
                ('destination_url_template', models.CharField(blank=True, help_text="URL template for notification links (e.g., '/jobs/{job_id}')", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently active')),
                ('is_urgent_by_default', models.BooleanField(default=False, help_text='Whether notifications using this template should be marked as urgent by default')),
                ('available_variables', models.JSONField(blank=True, default=dict, help_text='JSON object documenting available template variables (for reference)')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['type', 'channel'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'EMAIL'), ('websocket', 'WEBSOCKET'), ('both', 'BOTH'), ('push', 'PUSH')], default='websocket', help_text='The channel through which this notification was/will be delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('generic', 'GENERIC'), ('account_created', 'ACCOUNT_CREATED'), ('job_posted', 'JOB_POSTED'), ('job_applied', 'JOB_APPLIED'), ('application_status_update', 'APPLICATION_STATUS_UPDATE'), ('company_approved', 'COMPANY_APPROVED'), ('company_rejected', 'COMPANY_REJECTED'), ('admin_company_registration', 'ADMIN_COMPANY_REGISTRATION'), ('admin_user_registration', 'ADMIN_USER_REGISTRATION'), ('admin_job_posting', 'ADMIN_JOB_POSTING'), ('admin_system_alert', 'ADMIN_SYSTEM_ALERT'), ('admin_platform_activity', 'ADMIN_PLATFORM_ACTIVITY'), ('admin_report_generated', 'ADMIN_REPORT_GENERATED'), ('admin_company_verification', 'ADMIN_COMPANY_VERIFICATION'), ('admin_content_moderation', 'ADMIN_CONTENT_MODERATION'), ('admin_violation_report', 'ADMIN_VIOLATION_REPORT'), ('admin_maintenance', 'ADMIN_MAINTENANCE'), ('application_status_changed', 'APPLICATION_STATUS_CHANGED'), ('new_job_matches', 'NEW_JOB_MATCHES'), ('profile_completion_reminder', 'PROFILE_COMPLETION_REMINDER'), ('profile_viewed', 'PROFILE_VIEWED'), ('interview_scheduled', 'INTERVIEW_SCHEDULED'), ('interview_reminder', 'INTERVIEW_REMINDER'), ('job_expiring_soon', 'JOB_EXPIRING_SOON'), ('weekly_job_digest', 'WEEKLY_JOB_DIGEST'), ('saved_job_update', 'SAVED_JOB_UPDATE'), ('application_deadline_reminder', 'APPLICATION_DEADLINE_REMINDER'), ('application_submitted', 'APPLICATION_SUBMITTED'), ('application_pending', 'APPLICATION_PENDING'), ('application_under_review', 'APPLICATION_UNDER_REVIEW'), ('application_shortlisted', 'APPLICATION_SHORTLISTED'), ('application_interview_scheduled', 'APPLICATION_INTERVIEW_SCHEDULED'), ('application_accepted', 'APPLICATION_ACCEPTED'), ('application_offer_extended', 'APPLICATION_OFFER_EXTENDED'), ('application_rejected', 'APPLICATION_REJECTED'), ('application_withdrawn', 'APPLICATION_WITHDRAWN')], default='generic', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'channel', 'is_read'], name='ws_channel__user_id_c2146d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type', 'channel'], name='ws_channel__user_id_85587e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('type', 'channel')},
        ),
    ]
