# Generated by Django 5.1.1 on 2025-01-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
