# Generated by Django 5.1.1 on 2025-01-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_certification_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentclouduser',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
