# Generated by Django 5.1.1 on 2025-05-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0009_company_talentclouduser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentclouduser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
