# Generated by Django 5.2.6 on 2025-09-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_address_city_country_alter_talentclouduser_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentclouduser',
            old_name='profile_image_url',
            new_name='profile_image_path',
        ),
    ]
