# Generated by Django 5.2.6 on 2025-09-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_fileupload_deleted_at_fileupload_deletion_reason_and_more'),
        ('users', '0013_rename_profile_image_url_talentclouduser_profile_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentclouduser',
            name='profile_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_images', to='authentication.fileupload'),
        ),
    ]
