# Generated by Django 5.2.6 on 2025-09-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_talentclouduser_profile_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentclouduser',
            name='last_username_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentclouduser',
            name='old_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
