# Generated by Django 5.2.6 on 2025-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_talentclouduser_last_username_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentclouduser',
            name='last_username_changed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
