version: "3.9"
  
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django-react-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
