# Generated by Django 5.1.1 on 2025-08-21 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('profile_image', 'profile_image'), ('cover_letter', 'Cover Letter'), ('company_logo', 'Company Logo'), ('job_attachment', 'Job Attachment'), ('document', 'Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
