# Generated by Django 5.1.1 on 2025-09-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_fileupload_file_type_alter_fileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('profile_image', 'profile_image'), ('project_image', 'project_image'), ('cover_letter', 'Cover Letter'), ('company_logo', 'Company Logo'), ('job_attachment', 'Job Attachment'), ('document', 'Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('deleted', 'Deleted'), ('deletion_failed', 'Deletion failed')], default='pending', max_length=20),
        ),
    ]
