# Generated by Django 5.1.1 on 2025-09-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_fileupload_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_application', 'Pending job application'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('deleted', 'Deleted'), ('deletion_failed', 'Deletion failed')], default='pending', max_length=20),
        ),
    ]
