# Generated by Django 5.2.6 on 2025-09-22 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_fileupload_upload_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='deletion_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='is_protected',
            field=models.BooleanField(default=False, help_text="Protected files won't be auto-deleted"),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='marked_for_deletion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='reference_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of models referencing this file'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_application', 'Pending job application'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('orphaned', 'Orphaned (Not Referenced)'), ('marked_for_deletion', 'Marked for Deletion'), ('deleted', 'Deleted'), ('deletion_failed', 'Deletion failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['upload_status'], name='file_upload_upload__48a6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['last_accessed'], name='file_upload_last_ac_5beb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['marked_for_deletion_at'], name='file_upload_marked__a15ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_type', 'upload_status'], name='file_upload_file_ty_9f7073_idx'),
        ),
    ]
