# Generated by Django 5.2.6 on 2025-09-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_fileupload_deleted_at_fileupload_deletion_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload_url_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
