# Generated by Django 5.2.6 on 2025-09-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_fileupload_upload_url_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('profile_image', 'profile_image'), ('project_image', 'project_image'), ('cover_letter', 'Cover Letter'), ('company_image', 'Company Image'), ('company_logo', 'Company Logo'), ('job_attachment', 'Job Attachment'), ('document', 'Document')], max_length=20),
        ),
    ]
