# Generated by Django 5.1.1 on 2025-01-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_talentclouduser_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentclouduser',
            old_name='photo_url',
            new_name='profile_image_url',
        ),
    ]
