# Generated by Django 5.1.1 on 2025-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_talentclouduser_company_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyLoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('verification_code', models.CharField(max_length=255, unique=True)),
                ('expired_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
