# Generated by Django 5.1.1 on 2025-09-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_industry_company_company_image_urls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_image_urls',
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text="URL to the company's Cover image.", max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL to the company's logo.", max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='The official website URL of the company.', max_length=2048, null=True),
        ),
    ]
