# Generated by Django 5.1.1 on 2025-09-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_company_image_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
