# Generated by Django 5.2.6 on 2025-09-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_fileupload_deleted_at_fileupload_deletion_reason_and_more'),
        ('companies', '0006_company_company_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_cover_images', to='authentication.fileupload'),
        ),
        migrations.AddField(
            model_name='company',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_images', to='authentication.fileupload'),
        ),
    ]
