# Generated by Django 5.2.6 on 2025-09-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_cover_image_file_company_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='image_url',
        ),
    ]
