# Generated by Django 5.2.6 on 2025-09-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_remove_company_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text="URL to the company's Cover image.", max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL to the company's logo.", max_length=2048, null=True),
        ),
    ]
