# Generated by Django 5.2.6 on 2025-09-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_cover_image_url_company_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='image_url',
        ),
    ]
