# Generated by Django 5.1.1 on 2025-06-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_channel', '0003_chat_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
