# Generated by Django 5.1.1 on 2025-05-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
        ('job_seekers', '0025_jobseekerrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='roles',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='last_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='number_of_positions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='project_duration',
            field=models.CharField(blank=True, choices=[('less_than_1_month', 'Less than 1 month'), ('1_to_3_months', '1 to 3 months'), ('3_to_6_months', '3 to 6 months'), ('more_than_6_months', 'More than 6 months'), ('ongoing', 'Ongoing / Indefinite')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='job_seekers.jobseekerrole'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_mode',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('range', 'Range')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post', to='job_seekers.jobseekerspecialization'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], max_length=50),
        ),
    ]
