# Generated by Django 5.1.1 on 2025-05-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_remove_jobpost_roles_jobpost_last_application_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='year_of_experience',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
