# Generated by Django 5.1.1 on 2025-05-14 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_remove_jobpost_year_of_experience_and_more'),
        ('job_seekers', '0026_remove_jobseekeroccupation_year_of_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('job_post', models.ForeignKey(help_text='The job post that is bookmarked.', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='job_posting.jobpost')),
                ('job_seeker', models.ForeignKey(help_text='The job seeker who bookmarked the job.', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_jobs', to='job_seekers.jobseeker')),
            ],
            options={
                'verbose_name': 'Bookmarked Job',
                'verbose_name_plural': 'Bookmarked Jobs',
                'ordering': ['-created_at'],
                'unique_together': {('job_post', 'job_seeker')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('offer_extended', 'Offer Extended'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', help_text='The current status of the application.', max_length=50)),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter submitted with the application.', null=True)),
                ('application_resume_url', models.URLField(blank=True, help_text="URL of the resume submitted for this specific application (optional). If not provided, the seeker's current resume_url is typically used.", max_length=2048, null=True)),
                ('job_post', models.ForeignKey(help_text='The job post the seeker is applying for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_posting.jobpost')),
                ('job_seeker', models.ForeignKey(help_text='The job seeker who submitted the application.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_seekers.jobseeker')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
                'unique_together': {('job_post', 'job_seeker')},
            },
        ),
    ]
