# Generated by Django 5.1.1 on 2025-08-14 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_alter_jobpost_salary_mode_alter_jobpost_salary_type'),
        ('job_seekers', '0027_jobseeker_expected_salary_jobseeker_is_open_to_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('offer_extended', 'Offer Extended'), ('withdrawn', 'Withdrawn')], default='applied', help_text='The current status of the application.', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_post_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('active', 'Active'), ('draft', 'Draft'), ('expired', 'Expired')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='offered_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('hourly', 'hour'), ('monthly', 'month')], default='monthly', max_length=10),
        ),
        migrations.CreateModel(
            name='JobPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='job_posting.jobpost')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.jobseeker')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job_post', 'job_seeker')},
            },
        ),
    ]
