# Generated by Django 5.1.1 on 2025-08-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0006_jobapplication_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_resume_url',
            field=models.URLField(blank=True, help_text='URL of the job seeker resume.', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.URLField(blank=True, help_text='URL of the cover letter submitted for this specific application.', max_length=2048, null=True),
        ),
    ]
