# Generated by Django 5.1.1 on 2025-08-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0007_alter_jobapplication_application_resume_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='cover_letter',
            new_name='cover_letter_url',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='application_resume_url',
            new_name='resume_url',
        ),
    ]
