# Generated by Django 5.2.6 on 2025-09-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_fileupload_deleted_at_fileupload_deletion_reason_and_more'),
        ('job_posting', '0008_rename_cover_letter_jobapplication_cover_letter_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_cover_letters', to='authentication.fileupload'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_resumes', to='authentication.fileupload'),
        ),
    ]
