# Generated by Django 5.2.6 on 2025-09-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0010_remove_jobapplication_cover_letter_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_url',
            field=models.URLField(blank=True, help_text='URL of the cover letter submitted for this specific application.', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_url',
            field=models.URLField(blank=True, help_text='URL of the job seeker resume.', max_length=2048, null=True),
        ),
    ]
