# Generated by Django 5.2.6 on 2025-09-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0011_jobapplication_cover_letter_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_url',
        ),
    ]
