# Generated by Django 5.2.6 on 2025-09-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0012_remove_jobapplication_cover_letter_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
