# Generated by Django 5.2.6 on 2025-09-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0013_alter_jobpost_salary_max_alter_jobpost_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
