# Generated by Django 5.2.6 on 2025-10-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0014_alter_jobpost_salary_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='work_type',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=50),
        ),
    ]
