# Generated by Django 5.2.6 on 2025-10-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0015_alter_jobpost_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, unique=True)),
                ('search_count', models.PositiveIntegerField(db_index=True, default=1)),
                ('first_searched', models.DateTimeField(auto_now_add=True)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Term',
                'ordering': ['-search_count'],
                'constraints': [models.UniqueConstraint(fields=('keyword',), name='unique_keyword_entry')],
            },
        ),
    ]
