# Generated by Django 5.2.6 on 2025-10-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0016_searchterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='canonical_keyword',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
