# Generated by Django 5.2.6 on 2025-10-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0017_searchterm_canonical_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='daily_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='searchterm',
            name='weighted_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
