# Generated by Django 5.1.1 on 2025-01-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='title',
        ),
    ]
