# Generated by Django 5.1.1 on 2025-01-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='issue_date',
            new_name='issued_date',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='issuing_organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='certification_url',
            new_name='url',
        ),
    ]
