# Generated by Django 5.1.1 on 2025-01-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0011_rename_job_seeker_jobseekeroccupation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='on_boarding_step',
            new_name='onboarding_step',
        ),
    ]
