# Generated by Django 5.1.1 on 2025-01-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0014_jobseekeroccupation_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerOccupation',
        ),
    ]
