# Generated by Django 5.1.1 on 2025-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0019_jobseekersociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekercertification',
            name='credential_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
