# Generated by Django 5.1.1 on 2025-03-21 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0024_jobseekerexperienceyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('role_image_url', models.URLField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='jobseekerspecialization',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='jobseekeroccupation',
            name='industry',
        ),
        migrations.RemoveIndex(
            model_name='jobseekeroccupation',
            name='job_seekers_industr_70b0d9_idx',
        ),
        migrations.AddField(
            model_name='jobseekerspecialization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerrole',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_seekers.jobseekerspecialization'),
        ),
        migrations.AddField(
            model_name='jobseekeroccupation',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.jobseekerrole'),
        ),
        migrations.AddIndex(
            model_name='jobseekeroccupation',
            index=models.Index(fields=['specialization', 'role', 'experience_level'], name='job_seekers_special_f12c77_idx'),
        ),
        migrations.DeleteModel(
            name='JobSeekerIndustry',
        ),
    ]
