# Generated by Django 5.1.1 on 2025-05-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_remove_jobpost_year_of_experience_and_more'),
        ('job_seekers', '0025_jobseekerrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekeroccupation',
            name='year_of_experience',
        ),
        migrations.AddField(
            model_name='jobseekeroccupation',
            name='experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.DeleteModel(
            name='JobSeekerExperienceYear',
        ),
    ]
