# Generated by Django 5.1.1 on 2025-08-14 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0026_remove_jobseekeroccupation_year_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_open_to_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekeroccupation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupation', to='job_seekers.jobseeker'),
        ),
        migrations.AlterField(
            model_name='jobseekersociallink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='job_seekers.jobseeker'),
        ),
        migrations.CreateModel(
            name='JobSeekerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Project title', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of technologies, tools, or frameworks used in the project (e.g., ['Python', 'Django', 'React'])")),
                ('project_url', models.URLField(blank=True, help_text='URL to live project or demo', max_length=2048, null=True)),
                ('project_image_url', models.URLField(blank=True, help_text='URL to project screenshot or image', max_length=2048, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project completion date', null=True)),
                ('is_ongoing', models.BooleanField(default=False, help_text='Is this project still ongoing')),
                ('team_size', models.PositiveSmallIntegerField(blank=True, help_text='Number of team members (including yourself)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='job_seekers.jobseeker')),
            ],
            options={
                'verbose_name': 'Job Seeker Project',
                'verbose_name_plural': 'Job Seeker Projects',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSpecialSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('year_of_experience', models.PositiveSmallIntegerField(blank=True, help_text='Years of experience with this skill', null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.jobseekerskill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_skills', to='job_seekers.jobseeker')),
            ],
            options={
                'verbose_name': 'Job Seeker Special Skill',
                'verbose_name_plural': 'Job Seeker Special Skills',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
