# Generated by Django 5.1.1 on 2025-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0027_jobseeker_expected_salary_jobseeker_is_open_to_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerrole',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobseekerspecialization',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
