# Generated by Django 5.1.1 on 2025-09-02 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0028_alter_jobseekerrole_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerrole',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.jobseekerspecialization'),
        ),
    ]
