# Generated by Django 5.1.1 on 2025-09-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0029_alter_jobseekerrole_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekereducation',
            old_name='institution',
            new_name='custom_institution',
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Full university name', max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name', max_length=100, null=True)),
                ('university_type', models.CharField(choices=[('public', 'Public University'), ('private', 'Private University'), ('international', 'International University'), ('institute', 'Institute/College'), ('academy', 'Academy'), ('college', 'Education College'), ('other', 'Other')], default='public', max_length=20)),
                ('country', models.CharField(help_text='Country where university is located', max_length=100)),
                ('state_region', models.CharField(blank=True, help_text='State/Region in Myanmar', max_length=100, null=True)),
                ('website_url', models.URLField(blank=True, help_text='Official website', max_length=500, null=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Is this an officially verified university')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['country', 'state_region', 'name'],
                'indexes': [models.Index(fields=['country'], name='job_seekers_country_c56042_idx'), models.Index(fields=['state_region'], name='job_seekers_state_r_1f5b81_idx')],
            },
        ),
    ]
