# Generated by Django 5.1.1 on 2025-09-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0030_rename_institution_jobseekereducation_custom_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekereducation',
            name='custom_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
