# Generated by Django 5.1.1 on 2025-09-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0031_alter_jobseekereducation_custom_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekereducation',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.university'),
        ),
    ]
