# Generated by Django 5.1.1 on 2025-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0032_jobseekereducation_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekercertification',
            options={'ordering': ['-issued_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobseekereducation',
            options={'ordering': ['-start_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
