# Generated by Django 5.1.1 on 2025-09-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0032_jobseekereducation_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekercertification',
            options={'ordering': ['-issued_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobseekereducation',
            options={'ordering': ['-start_date', '-created_at']},
        ),
    ]
