# Generated by Django 5.1.1 on 2025-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0033_alter_jobseekercertification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['country', 'state', 'name'], 'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.RemoveIndex(
            model_name='university',
            name='job_seekers_state_r_1f5b81_idx',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='state_region',
            new_name='state',
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['state'], name='job_seekers_state_e4f73c_idx'),
        ),
    ]
