# Generated by Django 5.1.1 on 2025-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0034_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(help_text='Full university name', max_length=255),
        ),
    ]
