# Generated by Django 5.2.6 on 2025-09-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_fileupload_upload_status'),
        ('job_seekers', '0035_alter_university_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume_url',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Display name for this CV', max_length=255)),
                ('resume_path', models.URLField(blank=True, max_length=2048, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default CV?')),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.fileupload')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_documents', to='job_seekers.jobseeker')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('job_seeker',), name='unique_default_cv_per_jobseeker')],
            },
        ),
    ]
