# Generated by Django 5.2.6 on 2025-09-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0036_remove_jobseeker_resume_url_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, help_text='Display name for this CV', max_length=255, null=True),
        ),
    ]
