# Generated by Django 5.2.6 on 2025-09-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_fileupload_deleted_at_fileupload_deletion_reason_and_more'),
        ('job_seekers', '0037_alter_resume_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerproject',
            name='project_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_images', to='authentication.fileupload'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.fileupload'),
        ),
    ]
