# Generated by Django 5.2.6 on 2025-09-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0038_jobseekerproject_project_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerproject',
            name='project_image_url',
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
