# Generated by Django 5.2.6 on 2025-09-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0039_remove_jobseekerproject_project_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerproject',
            name='project_image_url',
            field=models.URLField(blank=True, help_text='URL to project screenshot or image', max_length=2048, null=True),
        ),
    ]
