# Generated by Django 5.2.6 on 2025-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0040_jobseekerproject_project_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
