# Generated by Django 5.1.1 on 2025-09-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0041_alter_university_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
