# Generated by Django 5.2.6 on 2025-09-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0042_alter_university_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerproject',
            name='project_image_url',
        ),
    ]
