# Generated by Django 5.2.6 on 2025-09-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0043_remove_jobseekerproject_project_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerexperience',
            options={'ordering': ['-start_date', '-created_at']},
        ),
    ]
