# Generated by Django 5.2.6 on 2025-10-21 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_fileupload_user'),
        ('job_seekers', '0044_alter_jobseekerexperience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekercertification',
            name='certification_image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_images', to='authentication.fileupload'),
        ),
    ]
