# Generated by Django 5.1.1 on 2025-06-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0004_bookmarkedjob_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_mode',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('range', 'Range')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
    ]
