# Generated by Django 5.1.1 on 2025-01-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0002_rename_name_skill_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
