# Generated by Django 5.1.1 on 2025-01-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0005_rename_issue_date_certification_issued_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_currently_attending',
            field=models.BooleanField(default=False),
        ),
    ]
