# Generated by Django 5.1.1 on 2025-01-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0006_education_is_currently_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='has_expiration_date',
            field=models.BooleanField(default=False),
        ),
    ]
