# Generated by Django 5.1.1 on 2025-01-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0007_certification_has_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
