# Generated by Django 5.1.1 on 2025-01-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0008_alter_certification_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='resume_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
