# Generated by Django 5.1.1 on 2025-01-17 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0009_alter_certification_url_alter_jobseeker_resume_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobSeekerIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Certification',
            new_name='JobSeekerCertification',
        ),
        migrations.RenameModel(
            old_name='Experience',
            new_name='JobSeekerExperience',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='JobSeekerSkill',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='on_boarding_step',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='JobSeekerEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_currently_attending', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='job_seekers.jobseeker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.jobseekerindustry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobSeekerOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.PositiveIntegerField()),
                ('experience_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.jobseekerexperiencelevel')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.jobseekerindustry')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='job_seekers.jobseeker')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.jobseekerspecialization')),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.AddIndex(
            model_name='jobseekeroccupation',
            index=models.Index(fields=['industry', 'specialization', 'experience_level'], name='job_seekers_industr_70b0d9_idx'),
        ),
    ]
