# Generated by Django 5.1.1 on 2025-01-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0010_jobseekerexperiencelevel_jobseekerindustry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekeroccupation',
            old_name='job_seeker',
            new_name='user',
        ),
    ]
