# Generated by Django 5.1.1 on 2025-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0012_rename_on_boarding_step_jobseeker_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekeroccupation',
            name='years_of_experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
