# Generated by Django 5.1.1 on 2025-01-21 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0013_alter_jobseekeroccupation_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeroccupation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekeroccupation',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekeroccupation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
