# Generated by Django 5.1.1 on 2025-01-21 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0015_delete_jobseekeroccupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('years_of_experience', models.PositiveIntegerField(null=True)),
                ('experience_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.jobseekerexperiencelevel')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.jobseekerindustry')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.jobseekerspecialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='job_seekers.jobseeker')),
            ],
            options={
                'indexes': [models.Index(fields=['industry', 'specialization', 'experience_level'], name='job_seekers_industr_70b0d9_idx')],
            },
        ),
    ]
