# Generated by Django 5.1.1 on 2025-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0017_remove_jobseekerskill_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerindustry',
            name='industry_image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerspecialization',
            name='specialization_image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
