# Generated by Django 5.1.1 on 2025-02-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0018_jobseekerindustry_industry_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('facebook_social_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('linkedin_social_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('behance_social_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('portfolio_social_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociallinks', to='job_seekers.jobseeker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
