# Generated by Django 5.1.1 on 2025-02-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0020_jobseekercertification_credential_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobSeekerLanguageProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('proficiency_level', models.CharField(choices=[('basic', 'Basic Level'), ('intermediate', 'Intermediate Level'), ('business', 'Business Level'), ('native', 'Native Level')], default='basic', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_proficiencies', to='job_seekers.jobseeker')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.spokenlanguage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
