# Generated by Django 5.1.1 on 2025-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0022_alter_jobseekerlanguageproficiency_proficiency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekersociallink',
            name='github_social_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
