# Generated by Django 5.1.1 on 2025-03-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0023_jobseekersociallink_github_social_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerExperienceYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('year', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='jobseekeroccupation',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='tagline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobseekeroccupation',
            name='year_of_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seekers.jobseekerexperienceyear'),
        ),
    ]
