name: Deploy to AWS

on:
     push:
          branches:
               - main

jobs:
     deploy:
          runs-on: ubuntu-latest

          steps:
          -    name: Deploy to VPS via SSH
               uses: appleboy/ssh-action@master
               with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USER }}
                    key: ${{ secrets.VPS_SSH_KEY }}
                    script: |
                              cd /home/youruser/yourproject
                              git pull origin main
                              docker-compose down
                              docker-compose up -d --build
